### ISSUE TITLE
new name for repo with mate in its name

### ISSUE THREAD

**Issue by sc0w** [mate-desktop/mate-submodules#1]
@mate-desktop/core-team 

maybe is better one name for this repo with **mate** in its name?

maybe **mate-libegg** ?

**Comment by raveit65** [comment]
@yetist 
Can you please re-check new repo mate-submodules-new?
`mate-submodules-new` can be renamed when old `mate-submodules` is deleted.

**Comment by yetist** [comment]
ok, you can delete mate-submodules repo, and rename mate-submodules-new to mate-submodules.

**Comment by yetist** [comment]
@raveit65 

I renamed `mate-submodules` to `mate-submodules-old`, and renamed the `mate-submodules-new` to `mate-submodules`, let me finished the caja, if everything is ok, we can safely delete `mate-submodules-old` repo.

**Comment by raveit65** [comment]
I will delete old repo now, so issue is resolved.
